name: e_learning_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  awesome_snackbar_content: ^0.1.3
  bloc: ^8.1.4
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_screenutil: ^5.9.0
  get_it: ^7.6.8
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.0.7
  device_info_plus: ^10.0.1
  permission_handler: ^11.3.1
  animated_toggle_switch: ^0.8.2
  intl_phone_field: ^3.2.0
  phone_text_field: ^0.0.7
  country_picker: ^2.0.25

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
flutter_intl:
  enabled: true
